# Generated by Django 5.2.5 on 2026-06-13 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', '一般會員'), ('editor', '編輯'), ('moderator', '版主'), ('admin', '管理員')], default='member', max_length=30, verbose_name='角色'),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='金鑰')),
                ('role', models.CharField(choices=[('member', '一般會員'), ('editor', '編輯'), ('moderator', '版主'), ('admin', '管理員')], default='member', help_text='此金鑰呼叫 API 時的有效角色（可高於或等於使用者本身）。', max_length=30, verbose_name='授權角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最後使用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': 'API 金鑰',
                'verbose_name_plural': 'API 金鑰',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
